app/urls.py
from django.urls import path
from .views import home, about, index

app_name = "app"

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('index/', index, name='index'),
]

cpfl_project/urls.py
from django.urls import include, path

urlpatterns = [
    # Other URL patterns for the project...
    path('', include('app.urls', namespace='app')),
]

app/models.py
from django.db import models

# Create your models here.


class CAPEXModels(models.Model):
    empresa = models.CharField(max_length=255, db_column='Empresa')
    codigo = models.CharField(max_length=255, db_column='Código')
    programa = models.CharField(max_length=255, db_column='Programa')
    status = models.CharField(max_length=255, db_column='Status da Obra')
    nome = models.CharField(max_length=255, db_column='Nome da Obra')
    descricao = models.CharField(max_length=255, db_column='Descrição')
    regiao = models.CharField(max_length=255, db_column='Região')
    criterio = models.CharField(max_length=255, db_column='Critério de Planejamento')
    classificacao = models.CharField(max_length=255, db_column='Classificação')
    tipo_obra = models.CharField(max_length=255, db_column='Tipo de Obra')
    ano_pese = models.CharField(max_length=255, db_column='Ano PESE')
    regiao_eletrica = models.CharField(max_length=255, db_column='Região Elétrica')
    tipo_projeto = models.CharField(max_length=255, db_column='Tipo do Projeto')
    subtipo_projeto = models.CharField(max_length=255, db_column='Subtipo')
    qtd_fisica = models.CharField(max_length=255, db_column='Qtd. Física')
    unidade = models.CharField(max_length=255, db_column='Unidade')
    valor_previsto_unitizacao = models.DecimalField(max_digits=20, decimal_places=2, db_column='Valor Previsto de Unitização')
    data_unitizacao = models.DateTimeField(db_column='Data Prevista de Unitização')
    responsavel = models.CharField(max_length=255, db_column='Responsável Planejamento')
    orcamento_total = models.DecimalField(max_digits=20, decimal_places=2, db_column='Orçamento Total')

app/views.py
from django.shortcuts import render
import pandas as pd
from .models import CAPEXModels

# views.py


def home(request):
    # Use separate lines for import statements
    if request.method == 'POST':
        file = request.FILES.get('file')
        if file is not None:
            try:
                # Explicitly catch ParserError instead of any Exception
                # to avoid hiding other exceptions.
                df = pd.read_excel(file, sheet_name="CAPEX")
                context = {'User': request.user, 'df': df, 'file_name': file.name}
                return render(request, 'home.html', context)

            except pd.errors.ParserError as e:
                # Handle ParserError explicitly
                return render(request, 'error.html', {'error': str(e)})
    return render(request, 'home.html')


def index(request):
    books = CAPEXModels.objects.all()
    return render(request, 'index.html', {'books': books})


def about(request):
    return render(request, 'about.html')

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About</h1>

{% endblock %}

app/templates/footer.html
<footer class="footer">
    <div class="content has-text-centered">
      <p>
        &copy; 2023 CPFL Energia. All rights reserved.
      </p>
    </div>
</footer>
  

app/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

app/templates/home.html
{% include 'header.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<body>
    {% include 'navbar.html' %}
    <section class="section has-background-light" style="padding-top: 0px;">
        <div class="container">
            <div class="hero-body">
                <p class="title">
                    Olá {{ User }}
                </p>
                <p class="subtitle">
                    Bem-vindo ao programa de cálculo econômico das obras do PESE
                </p>
            </div>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="block">
                    <div class="file is-centered is-boxed is-success has-name">
                        <label class="file-label">
                            <input class="file-input" type="file" name="file">
                            <span class="file-cta">
                                <span class="file-icon">
                                    <i class="fas fa-upload"></i>
                                </span>
                                <span class="file-label">
                                    Arquivo para upload
                                </span>
                            </span>
                            {% comment %} span with file_name or "Nenhum arquivo selecionado" {% endcomment %}
                            <span class="file-name">
                                {% if file_name %}
                                {{ file_name }}
                                {% else %}
                                Nenhum arquivo selecionado
                                {% endif %}
                            </span>
                        </label>
                    </div>
                    <div class="block">
                        <div class="buttons is-centered">
                            <button class="button is-success" type="submit">Enviar</button>
                        </div>
            </form>
            {% if not df.empty %}
            <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                <thead>
                    <tr>
                        {% for column in df.columns %}
                        <th>{{ column }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for row in df.values %}
                    <tr>
                        {% for value in row %}
                        <td>{{ value }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
            <nav class="panel">
                <p class="panel-heading">
                    Projetos
                </p>
                <div class="panel-block">
                    <p class="control has-icons-left">
                        <input class="input" type="text" placeholder="Search">
                        <span class="icon is-left">
                            <i class="fas fa-search" aria-hidden="true"></i>
                        </span>
                    </p>
                </div>
                <a class="panel-block is-active">
                    <span class="panel-icon">
                        <i class="fas fa-solid fa-file-excel" aria-hidden="true"></i>
                    </span>
                    bulma
            </nav>
        </div>
    </section>
</body>
{% include 'footer.html' %}
```

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Books</h1>
<ul>
    {% for book in books %}
        <li>{{ book.title }} by {{ book.author }}</li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/navbar.html
<nav class="navbar is-transparent">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                {% load static %}
                <img src="{% static 'img/logo.png' %}" alt="Logo" width="30">
            </a>
        </div>

        <div class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item" href="{% url 'app:home' %}">
                    Home
                </a>
                <a class="navbar-item" href="{% url 'app:about' %}">
                    About
                </a>
            </div>
        </div>
    </div>
</nav>